server:
  port: 8080

spring:
  application:
    name: account
  profiles:
    include: account-mysql,account-mybatis,user-mysql,user-mybatis
    active: dev

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

uim:
  index: "forward:/${spring.application.name}/v1/index.html"