server:
  port: 8080

spring:
  application:
    name: account
  profiles:
    include: account-mysql,account-mybatis
    active: dev

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true